[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = "default-src '*' data:; img-src '*' data:; media-src '*' data:"
    Strict-Transport-Security = "max-age=7755311; includeSubDomains"
    Feature-Policy = "microphone '*'; camera '*'; fullscreen '*'; autoplay '*'"
    Permissions-Policy = "microphone=(*); camera=(*); fullscreen=(*) autoplay=(*);"
